name: Build ESP8266 Binary

on:
  push:
    paths:
      - '**/*.ino'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: 0.35.3        # pin the release

    - name: Install ESP8266 platform
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266

    - name: Compile sketch to bin/
      run: |
        mkdir -p bin
        arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 NodeMCU_OTA --output-dir bin

    - name: Upload firmware from bin/
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/*.bin