name: Build ESP8266 Firmware

on:
  push:
    paths:
      - '**/*.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile NodeMCU Sketch
      uses: arduino/compile-sketches@v1
      with:
        fqbn: esp8266:esp8266:nodemcuv2
        platforms: |
          - name: esp8266:esp8266
            source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        sketch-paths: |
          - .
        verbose: false
        sketches-report-path: sketches-report

    - name: Find and move .bin
      run: |
        mkdir -p bin
        find . -name "*.bin" -exec cp {} bin/ \;

    - name: Upload firmware.bin
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/*.bin